"""empty message

Revision ID: d012f7a32718
Revises: 24cd465433f7
Create Date: 2024-03-18 08:33:57.606138

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d012f7a32718"
down_revision = "24cd465433f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
