"""empty message

Revision ID: 24cd465433f7
Revises: aa449f0f5590
Create Date: 2024-03-14 17:21:59.005841

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "24cd465433f7"
down_revision = "aa449f0f5590"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contacts",
        "discription",
        existing_type=sa.TEXT(),
        comment="Описание контаката",
        existing_comment="Описание контакат",
        existing_nullable=True,
    )
    op.alter_column(
        "contacts",
        "created_at",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_comment="Дата создания",
        existing_nullable=True,
    )
    op.alter_column(
        "contacts",
        "updated_at",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_comment="Дата обновления",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contacts",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_comment="Дата обновления",
        existing_nullable=True,
    )
    op.alter_column(
        "contacts",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_comment="Дата создания",
        existing_nullable=True,
    )
    op.alter_column(
        "contacts",
        "discription",
        existing_type=sa.TEXT(),
        comment="Описание контакат",
        existing_comment="Описание контаката",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
