"""empty message

Revision ID: aa449f0f5590
Revises: 819cbf6e030b
Create Date: 2024-03-14 14:43:01.400687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa449f0f5590'
down_revision = '819cbf6e030b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор'),
    sa.Column('name', sa.String(), nullable=False, comment='Имя контакта'),
    sa.Column('discription', sa.Text(), nullable=True, comment='Описание контакат'),
    sa.Column('created_at', sa.Date(), nullable=True, comment='Дата создания'),
    sa.Column('updated_at', sa.Date(), nullable=True, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id'),
    comment='Книга контактов'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
