version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
      network: host
    image: src:${SRC_VERSION:-latest}
    restart: always
    ports:
      # Exposes application port.
      - "8001:8000"
    env_file:
    - .env
    environment:
      SRC_HOST: 0.0.0.0
      SRC_DB_HOST: 192.168.0.134
      SRC_DB_PORT: 5432
      SRC_DB_USER: postgres
      SRC_DB_PASS: postgres
      SRC_DB_BASE: help_igor_app
    networks:
      - app-network

volumes:
  src-db-data:
    name: src-db-data

networks:
  app-network:
    driver: bridge
