version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: src:${SRC_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      SRC_HOST: 0.0.0.0
      SRC_DB_HOST: src-db
      SRC_DB_PORT: 5432
      SRC_DB_USER: src
      SRC_DB_PASS: src
      SRC_DB_BASE: src


volumes:
  src-db-data:
    name: src-db-data
